FROM apache/airflow:2.8.1-python3.10

USER root
RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential \
    libpq-dev \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

USER airflow

RUN pip install --no-cache-dir \
    duckdb==0.10.0 \
    faker==23.2.0 \
    boto3==1.34.44 \
    psycopg2-binary==2.9.9 \
    pandas==2.2.0 \
    pyarrow==15.0.0 \
    presidio-analyzer==2.2.33 \
    presidio-anonymizer==2.2.33 \
    streamlit==1.31.1
